language: python
sudo: false
python: 3.6
env:
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
before_install:
    # Work around https://github.com/travis-ci/travis-ci/issues/8363
    - pyenv global system 3.5
